mappings:
  CMSBatchAction_Publish: SilverStripe\CMS\BatchActions\CMSBatchAction_Publish
  CMSBatchAction_Unpublish: SilverStripe\CMS\BatchActions\CMSBatchAction_Unpublish
  CMSBatchAction_Archive: SilverStripe\CMS\BatchActions\CMSBatchAction_Archive
  CMSBatchAction_Restore: SilverStripe\CMS\BatchActions\CMSBatchAction_Restore
  CMSBatchAction_Delete: SilverStripe\CMS\BatchActions\CMSBatchAction_Delete
  CMSMain: SilverStripe\CMS\Controllers\CMSMain
  CMSPageAddController: SilverStripe\CMS\Controllers\CMSPageAddController
  CMSPageEditController: SilverStripe\CMS\Controllers\CMSPageEditController
  CMSPageHistoryController: SilverStripe\CMS\Controllers\CMSPageHistoryController
  CMSPagesController: SilverStripe\CMS\Controllers\CMSPagesController
  CMSPageSettingsController: SilverStripe\CMS\Controllers\CMSPageSettingsController
  CMSSiteTreeFilter: SilverStripe\CMS\Controllers\CMSSiteTreeFilter
  CMSSiteTreeFilter_PublishedPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_PublishedPages
  CMSSiteTreeFilter_DeletedPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_DeletedPages
  CMSSiteTreeFilter_ChangedPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_ChangedPages
  CMSSiteTreeFilter_StatusRemovedFromDraftPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_StatusRemovedFromDraftPages
  CMSSiteTreeFilter_StatusDraftPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_StatusDraftPages
  CMSSiteTreeFilter_StatusDeletedPages: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_StatusDeletedPages
  CMSSiteTreeFilter_Search: SilverStripe\CMS\Controllers\CMSSiteTreeFilter_Search
  ContentController: SilverStripe\CMS\Controllers\ContentController
  ErrorPageControllerExtension: SilverStripe\CMS\Controllers\ErrorPageControllerExtension
  ErrorPageFileExtension: SilverStripe\CMS\Controllers\ErrorPageFileExtension
  LeftAndMainPageIconsExtension: SilverStripe\CMS\Controllers\LeftAndMainPageIconsExtension
  ModelAsController: SilverStripe\CMS\Controllers\ModelAsController
  OldPageRedirector: SilverStripe\CMS\Controllers\OldPageRedirector
  RootURLController: SilverStripe\CMS\Controllers\RootURLController
  SilverStripeNavigator: SilverStripe\CMS\Controllers\SilverStripeNavigator
  SilverStripeNavigatorItem: SilverStripe\CMS\Controllers\SilverStripeNavigatorItem
  SilverStripeNavigatorItem_CMSLink: SilverStripe\CMS\Controllers\SilverStripeNavigatorItem_CMSLink
  SilverStripeNavigatorItem_StageLink: SilverStripe\CMS\Controllers\SilverStripeNavigatorItem_StageLink
  SilverStripeNavigatorItem_LiveLink: SilverStripe\CMS\Controllers\SilverStripeNavigatorItem_LiveLink
  SilverStripeNavigatorItem_ArchiveLink: SilverStripe\CMS\Controllers\SilverStripeNavigatorItem_ArchiveLink
  SiteTreeURLSegmentField: SilverStripe\CMS\Forms\SiteTreeURLSegmentField
  SiteTreeURLSegmentField_Readonly: SilverStripe\CMS\Forms\SiteTreeURLSegmentField_Readonly
  CurrentPageIdentifier: SilverStripe\CMS\Model\CurrentPageIdentifier
  ErrorPage: SilverStripe\CMS\Model\ErrorPage
  ErrorPage_Controller: SilverStripe\CMS\Model\ErrorPage_Controller
  RedirectorPage: SilverStripe\CMS\Model\RedirectorPage
  RedirectorPage_Controller: SilverStripe\CMS\Model\RedirectorPage_Controller
  SiteTree: SilverStripe\CMS\Model\SiteTree
  SiteTreeExtension: SilverStripe\CMS\Model\SiteTreeExtension
  SiteTreeFileExtension: SilverStripe\CMS\Model\SiteTreeFileExtension
  SiteTreeFolderExtension: SilverStripe\CMS\Model\SiteTreeFolderExtension
  SiteTreeLinkTracking: SilverStripe\CMS\Model\SiteTreeLinkTracking
  SiteTreeLinkTracking_Parser: SilverStripe\CMS\Model\SiteTreeLinkTracking_Parser
  VirtualPage: SilverStripe\CMS\Model\VirtualPage
  VirtualPage_Controller: SilverStripe\CMS\Model\VirtualPage_Controller
  BrokenFilesReport: SilverStripe\CMS\Reports\BrokenFilesReport
  SideReport_BrokenFiles: SilverStripe\CMS\Reports\SideReport_BrokenFiles
  BrokenLinksReport: SilverStripe\CMS\Reports\BrokenLinksReport
  SideReport_BrokenLinks: SilverStripe\CMS\Reports\SideReport_BrokenLinks
  BrokenRedirectorPagesReport: SilverStripe\CMS\Reports\BrokenRedirectorPagesReport
  SideReport_BrokenRedirectorPages: SilverStripe\CMS\Reports\SideReport_BrokenRedirectorPages
  BrokenVirtualPagesReport: SilverStripe\CMS\Reports\BrokenVirtualPagesReport
  SideReport_BrokenVirtualPages: SilverStripe\CMS\Reports\SideReport_BrokenVirtualPages
  EmptyPagesReport: SilverStripe\CMS\Reports\EmptyPagesReport
  SideReport_EmptyPages: SilverStripe\CMS\Reports\SideReport_EmptyPages
  RecentlyEditedReport: SilverStripe\CMS\Reports\RecentlyEditedReport
  SideReport_RecentlyEdited: SilverStripe\CMS\Reports\SideReport_RecentlyEdited
  ContentControllerSearchExtension: SilverStripe\CMS\Search\ContentControllerSearchExtension
  SearchForm: SilverStripe\CMS\Search\SearchForm
  MigrateSiteTreeLinkingTask: SilverStripe\CMS\Tasks\MigrateSiteTreeLinkingTask
  RemoveOrphanedPagesTask: SilverStripe\CMS\Tasks\RemoveOrphanedPagesTask
  SiteTreeMaintenanceTask: SilverStripe\CMS\Tasks\SiteTreeMaintenanceTask
  CMSBatchActionsTest: SilverStripe\CMS\Tests\Controllers\CMSBatchActionsTest
  CMSMainTest: SilverStripe\CMS\Tests\Controllers\CMSMainTest
  CMSMainTest_ClassA: SilverStripe\CMS\Tests\Controllers\CMSMainTest_ClassA
  CMSMainTest_ClassB: SilverStripe\CMS\Tests\Controllers\CMSMainTest_ClassB
  CMSMainTest_NotRoot: SilverStripe\CMS\Tests\Controllers\CMSMainTest_NotRoot
  CMSMainTest_HiddenClass: SilverStripe\CMS\Tests\Controllers\CMSMainTest_HiddenClass
  CMSPageHistoryControllerTest: SilverStripe\CMS\Tests\Controllers\CMSPageHistoryControllerTest
  CMSSiteTreeFilterTest: SilverStripe\CMS\Tests\Controllers\CMSSiteTreeFilterTest
  ContentControllerPermissionsTest: SilverStripe\CMS\Tests\Controllers\ContentControllerPermissionsTest
  ContentControllerSearchExtensionTest: SilverStripe\CMS\Tests\Controllers\ContentControllerSearchExtensionTest
  ContentControllerTest: SilverStripe\CMS\Tests\Controllers\ContentControllerTest
  ContentControllerTest_Page: SilverStripe\CMS\Tests\Controllers\ContentControllerTest_Page
  ContentControllerTest_Page_Controller: SilverStripe\CMS\Tests\Controllers\ContentControllerTest_Page_Controller
  ContentControllerTestPageWithoutController: SilverStripe\CMS\Tests\Controllers\ContentControllerTestPageWithoutController
  ContentControllerTestPage: SilverStripe\CMS\Tests\Controllers\ContentControllerTestPage
  ContentControllerTestPage_Controller: SilverStripe\CMS\Tests\Controllers\ContentControllerTestPage_Controller
  ModelAsControllerTest: SilverStripe\CMS\Tests\Controllers\ModelAsControllerTest
  RootURLControllerTest: SilverStripe\CMS\Tests\Controllers\RootURLControllerTest
  SilverStripeNavigatorTest: SilverStripe\CMS\Tests\Controllers\SilverStripeNavigatorTest
  SilverStripeNavigatorTest_TestItem: SilverStripe\CMS\Tests\Controllers\SilverStripeNavigatorTest_TestItem
  SilverStripeNavigatorTest_ProtectedTestItem: SilverStripe\CMS\Tests\Controllers\SilverStripeNavigatorTest_ProtectedTestItem
  ErrorPageFileExtensionTest: SilverStripe\CMS\Tests\Model\ErrorPageFileExtensionTest
  ErrorPageTest: SilverStripe\CMS\Tests\Model\ErrorPageTest
  FileLinkTrackingTest: SilverStripe\CMS\Tests\Model\FileLinkTrackingTest
  RedirectorPageTest: SilverStripe\CMS\Tests\Model\RedirectorPageTest
  RedirectorPageTest_RedirectExtension: SilverStripe\CMS\Tests\Model\RedirectorPageTest_RedirectExtension
  SiteTreeActionsTest: SilverStripe\CMS\Tests\Model\SiteTreeActionsTest
  SiteTreeActionsTest_Page: SilverStripe\CMS\Tests\Model\SiteTreeActionsTest_Page
  SiteTreeBacklinksTest: SilverStripe\CMS\Tests\Model\SiteTreeBacklinksTest
  SiteTreeBacklinksTest_DOD: SilverStripe\CMS\Tests\Model\SiteTreeBacklinksTest_DOD
  SiteTreeBrokenLinksTest: SilverStripe\CMS\Tests\Model\SiteTreeBrokenLinksTest
  SiteTreeHTMLEditorFieldTest: SilverStripe\CMS\Tests\Model\SiteTreeHTMLEditorFieldTest
  SiteTreeLinkTrackingTest: SilverStripe\CMS\Tests\Model\SiteTreeLinkTrackingTest
  SiteTreePermissionsTest: SilverStripe\CMS\Tests\Model\SiteTreePermissionsTest
  SiteTreeTest: SilverStripe\CMS\Tests\Model\SiteTreeTest
  SiteTreeTest_PageNode: SilverStripe\CMS\Tests\Model\SiteTreeTest_PageNode
  SiteTreeTest_PageNode_Controller: SilverStripe\CMS\Tests\Model\SiteTreeTest_PageNode_Controller
  SiteTreeTest_Conflicted: SilverStripe\CMS\Tests\Model\SiteTreeTest_Conflicted
  SiteTreeTest_Conflicted_Controller: SilverStripe\CMS\Tests\Model\SiteTreeTest_Conflicted_Controller
  SiteTreeTest_NullHtmlCleaner: SilverStripe\CMS\Tests\Model\SiteTreeTest_NullHtmlCleaner
  SiteTreeTest_ClassA: SilverStripe\CMS\Tests\Model\SiteTreeTest_ClassA
  SiteTreeTest_ClassB: SilverStripe\CMS\Tests\Model\SiteTreeTest_ClassB
  SiteTreeTest_ClassC: SilverStripe\CMS\Tests\Model\SiteTreeTest_ClassC
  SiteTreeTest_ClassD: SilverStripe\CMS\Tests\Model\SiteTreeTest_ClassD
  SiteTreeTest_ClassE: SilverStripe\CMS\Tests\Model\SiteTreeTest_ClassE
  SiteTreeTest_ClassCext: SilverStripe\CMS\Tests\Model\SiteTreeTest_ClassCext
  SiteTreeTest_NotRoot: SilverStripe\CMS\Tests\Model\SiteTreeTest_NotRoot
  SiteTreeTest_StageStatusInherit: SilverStripe\CMS\Tests\Model\SiteTreeTest_StageStatusInherit
  SiteTreeTest_Extension: SilverStripe\CMS\Tests\Model\SiteTreeTest_Extension
  SiteTreeTest_AdminDenied: SilverStripe\CMS\Tests\Model\SiteTreeTest_AdminDenied
  SiteTreeTest_ExtensionA: SilverStripe\CMS\Tests\Model\SiteTreeTest_ExtensionA
  SiteTreeTest_ExtensionB: SilverStripe\CMS\Tests\Model\SiteTreeTest_ExtensionB
  SiteTreeTest_AdminDeniedExtension: SilverStripe\CMS\Tests\Model\SiteTreeTest_AdminDeniedExtension
  VirtualPageTest: SilverStripe\CMS\Tests\Model\VirtualPageTest
  VirtualPageTest_ClassA: SilverStripe\CMS\Tests\Model\VirtualPageTest_ClassA
  VirtualPageTest_ClassA_Controller: SilverStripe\CMS\Tests\Model\VirtualPageTest_ClassA_Controller
  VirtualPageTest_ClassB: SilverStripe\CMS\Tests\Model\VirtualPageTest_ClassB
  VirtualPageTest_ClassC: SilverStripe\CMS\Tests\Model\VirtualPageTest_ClassC
  VirtualPageTest_NotRoot: SilverStripe\CMS\Tests\Model\VirtualPageTest_NotRoot
  VirtualPageTest_TestDBField: SilverStripe\CMS\Tests\Model\VirtualPageTest_TestDBField
  VirtualPageTest_VirtualPageSub: SilverStripe\CMS\Tests\Model\VirtualPageTest_VirtualPageSub
  VirtualPageTest_PageExtension: SilverStripe\CMS\Tests\Model\VirtualPageTest_PageExtension
  VirtualPageTest_PageWithAllowedChildren: SilverStripe\CMS\Tests\Model\VirtualPageTest_PageWithAllowedChildren
  CmsReportsTest: SilverStripe\CMS\Tests\Reports\CmsReportsTest
  CMSMainSearchFormTest: SilverStripe\CMS\Tests\Search\CMSMainSearchFormTest
  ZZZSearchFormTest: SilverStripe\CMS\Tests\Search\ZZZSearchFormTest
  MigrateSiteTreeLinkingTaskTest: SilverStripe\CMS\Tests\Tasks\MigrateSiteTreeLinkingTaskTest
  RemoveOrphanedPagesTaskTest: SilverStripe\CMS\Tests\Tasks\RemoveOrphanedPagesTaskTest
